name: Run-CI-Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  checks_and_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: generate html page
        run: 
          chmod 0755 gen_html.sh && ./gen_html.sh
        shell: bash

